[package]
name = 'UseOracleInContractWithPyth'
version = '0.1.0'
upgrade_policy = "compatible"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.Pyth]
git = 'https://github.com/pyth-network/pyth-crosschain.git'
rev = 'main'
subdir = 'aptos/contracts/'

[addresses]
use_oracle="0xAAAAAAAA"
aptos_framework = "0x1"
pyth = "0xe2f37b8ac45d29d5ea23eb7d16dd3f7a7ab6426f5a998d6c23ecd3ae8d9d29eb"
wormhole = "0x251011524cd0f76881f16e7c2d822f0c1c9510bfd2430ba24e1b3d52796df204"
deployer = "0x277fa055b6a73c42c0662d5236c65c864ccbf2d4abd21f174a30c8b786eab84b"
